### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference

### ISSUE THREAD

**Issue by TomasWard1** [rafaelsetragni/awesome_notifications_fcm#22]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**
When receiving an fcm silent notification, I get this error and the app crashes.

## **2 - Provide us as much information as possible**
Happens both in emulator and in physical device. Android.
Error message:

```Dart
D/AndroidRuntime(21561): Shutting down VM
E/AndroidRuntime(21561): FATAL EXCEPTION: main
E/AndroidRuntime(21561): Process: com.tomasward.fredi, PID: 21561
E/AndroidRuntime(21561): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
E/AndroidRuntime(21561): 	at com.fantastic.manage_calendar_events.ManageCalendarEventsPlugin.onDetachedFromEngine(ManageCalendarEventsPlugin.java:63)
E/AndroidRuntime(21561): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime(21561): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
E/AndroidRuntime(21561): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
E/AndroidRuntime(21561): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
E/AndroidRuntime(21561): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:427)
E/AndroidRuntime(21561): 	at me.carda.awesome_notifications_fcm.FcmDartBackgroundExecutor$2.run(FcmDartBackgroundExecutor.java:211)
E/AndroidRuntime(21561): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(21561): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21561): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(21561): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(21561): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21561): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(21561): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (21561): Sending signal. PID: 21561 SIG: 9
```

## **3 - How To Reproduce the Error**
Send and receive a firebase fcm notification with the following json: (scheduled is true):
```
      "to": fcmToken,
      "priority": "high",
      if (!scheduled) "mutable_content": true,
      if (scheduled) 'content_available': true,
      if (!scheduled) "notification": {"title": title, "body": body},
      "data": {
        "content": {
          "id": notificationId,
          "channelKey": "basic_channel",
          "displayOnForeground": false,
          "notificationLayout": (iconUrl != null) ? "BigPicture" : 'Default',
          if (iconUrl != null) "largeIcon": iconUrl,
          if (bigPictureUrl != null) "bigPicture": bigPictureUrl,
          "showWhen": true,
          "autoDismissible": true,
          "privacy": "Private",
          "payload": {
            'title': title,
            'body': body,
            'type': type.toString(),
            'scheduled': scheduled,
            if (senderId != null) 'sender_id': senderId,
            if (groupId != null) 'group_id': groupId,
            if (itemId != null) 'item_id': itemId,
            if (scheduled) 'schedule': schedule.toString(),
          }
        },
      }
    };
```

## **4 - Expected behavior**
Receive the silent notification and handle it with the handler

**Comment by TomasWard1** [comment]
Follow up: Which would be the best practice to send a scheduled notification through fcm?

**Comment by rafaelsetragni** [comment]
Your event methods are static ones? You need to implement your listeners exactly how its demonstrate on the [How to show Local Notifications](https://pub.dev/packages/awesome_notifications#-how-to-show-local-notifications) topic and on [example page](https://pub.dev/packages/awesome_notifications/example)

Also, you can't use lambda functions to listen notification events. In case you need to get the current context, you can use the navigatorKey.

**Comment by TomasWard1** [comment]
This is how I am initializing my listeners:
``` 
static Future<void> initializeRemoteNotifications({required bool debug}) async {
    await AwesomeNotificationsFcm().initialize(
        onFcmSilentDataHandle: myFCMSilentDataHandle,
        onFcmTokenHandle: myFcmTokenHandle,
        onNativeTokenHandle: myNativeTokenHandle,
        licenseKeys: [
          // me.carda.awesomeNotificationsFcmExample
          'B3J3yxQbzzyz0KmkQR6rDlWB5N68sTWTEMV7k9HcPBroUh4RZ/Og2Fv6Wc/lE'
              '2YaKuVY4FUERlDaSN4WJ0lMiiVoYIRtrwJBX6/fpPCbGNkSGuhrx0Rekk'
              '+yUTQU3C3WCVf2D534rNF3OnYKUjshNgQN8do0KAihTK7n83eUD60=',

          // me.carda.awesome_notifications_fcm_example
          'UzRlt+SJ7XyVgmD1WV+7dDMaRitmKCKOivKaVsNkfAQfQfechRveuKblFnCp4'
              'zifTPgRUGdFmJDiw1R/rfEtTIlZCBgK3Wa8MzUV4dypZZc5wQIIVsiqi0Zhaq'
              'YtTevjLl3/wKvK8fWaEmUxdOJfFihY8FnlrSA48FW94XWIcFY=',
        ],
        debug: debug);
  }
```

And here my functions:
```
  @pragma("vm:entry-point")
  static Future<void> myFCMSilentDataHandle(FcmSilentData silentData) async {
    print('"SilentData": ${silentData.toString()}');
  }
```

**Comment by TomasWard1** [comment]
Nevertheless, I have made a workaround for silent notifications:
I send a fcm with a `notification` section, but I set `displayIOnBackgroun` and `display on Foreground` to `false`.
When I receive this, I create a new notification directly with the plugin which does display.

**Comment by rafaelsetragni** [comment]
But this is the best way to do. And you must use silent pushes to create remote schedules.
